name: cs234_final_project
channels:
  - conda-forge  
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pip
  - matplotlib
  - loguru
  - pandas
  - coloredlogs
  - docopt
  - tqdm
  - pip:
      - torch